export enum ModuleKey {
  Dashboard = 'dashboard',
  Crm = 'crm',
  Analytics = 'analytics',
  AiAssistant = 'ai-assistant',
  Campaigns = 'campaigns',
  Documents = 'documents',
  Scoring = 'scoring',
  Qr = 'qr',
  Notifications = 'notifications',
  Users = 'users',
  Roles = 'roles',
  Settings = 'settings',
  Workflows = 'workflows',
  // Proptech
  ProptechDashboard = 'proptech',
  ProptechProfile = 'proptech-profile',
  ProptechValuations = 'proptech-valuations',
  ProptechProperties = 'proptech-properties',
  ProptechMatching = 'proptech-matching',
  ProptechVisits = 'proptech-visits',
  ProptechContracts = 'proptech-contracts',
  ProptechLeads = 'proptech-leads',
  ProptechClients = 'proptech-clients',
  ProptechAnalytics = 'proptech-analytics',
  ProptechSales = 'proptech-sales',
  ProptechReports = 'proptech-reports',
  ProptechMySales = 'proptech-my-sales',
}
