export enum Permission {
  ViewDashboard = 'dashboard:view',
  ManageUsers = 'users:manage',
  ManageRoles = 'roles:manage',
  ManageSettings = 'settings:manage',
  AccessCrm = 'crm:access',
  AccessAnalytics = 'analytics:access',
  AccessAi = 'ai:access',
  AccessCampaigns = 'campaigns:access',
  AccessDocuments = 'documents:access',
  AccessScoring = 'scoring:access',
  AccessQr = 'qr:access',
  AccessNotifications = 'notifications:access',
  AccessWorkflows = 'workflows:access',
  // Proptech
  AccessProptech = 'proptech:access',
  PropPropertyCreate = 'proptech.property.create',
  PropPropertyRead = 'proptech.property.read',
  PropPropertyPublish = 'proptech.property.publish',
  PropMatchingGenerate = 'proptech.matching.generate',
  PropContractReviewAi = 'proptech.contract.review_ai',
  PropMarketInsightsRead = 'proptech.market_insights.read',
}
