import { Permission } from '@core/enums/permissions.enum';
import { Role } from '@core/enums/roles.enum';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.Admin]: Object.values(Permission),
  [Role.Manager]: [
    Permission.ViewDashboard,
    Permission.AccessCrm,
    Permission.AccessAnalytics,
    Permission.AccessAi,
    Permission.AccessCampaigns,
    Permission.AccessDocuments,
    Permission.AccessScoring,
    Permission.AccessQr,
    Permission.AccessNotifications,
    Permission.AccessWorkflows,
    Permission.AccessProptech,
    Permission.PropPropertyRead,
    Permission.PropPropertyCreate,
    Permission.PropMatchingGenerate,
    Permission.PropContractReviewAi,
    Permission.PropMarketInsightsRead,
  ],
  [Role.Operator]: [
    Permission.ViewDashboard,
    Permission.AccessCrm,
    Permission.AccessCampaigns,
    Permission.AccessDocuments,
    Permission.AccessQr,
    Permission.AccessNotifications,
    Permission.AccessProptech,
    Permission.PropPropertyRead,
  ],
  [Role.Viewer]: [Permission.ViewDashboard, Permission.AccessAnalytics, Permission.PropPropertyRead, Permission.PropMarketInsightsRead],
  [Role.AgencyAdmin]: [
    Permission.ViewDashboard,
    Permission.AccessProptech,
    Permission.PropPropertyCreate,
    Permission.PropPropertyRead,
    Permission.PropPropertyPublish,
    Permission.PropMatchingGenerate,
    Permission.PropContractReviewAi,
    Permission.PropMarketInsightsRead,
    Permission.AccessCrm,
    Permission.AccessDocuments,
    Permission.AccessNotifications,
  ],
  [Role.Agent]: [
    Permission.ViewDashboard,
    Permission.AccessProptech,
    Permission.PropPropertyCreate,
    Permission.PropPropertyRead,
    Permission.PropMatchingGenerate,
    Permission.AccessCrm,
    Permission.AccessNotifications,
  ],
  [Role.Owner]: [
    Permission.ViewDashboard,
    Permission.AccessProptech,
    Permission.PropPropertyRead,
    Permission.PropPropertyCreate,
  ],
  [Role.Client]: [
    Permission.ViewDashboard,
    Permission.AccessProptech,
    Permission.PropPropertyRead,
    Permission.PropMatchingGenerate,
  ],
  [Role.LegalReviewer]: [
    Permission.ViewDashboard,
    Permission.AccessProptech,
    Permission.PropPropertyRead,
    Permission.PropContractReviewAi,
    Permission.AccessDocuments,
  ],
};
