export const ROUTES = {
  home: '/',
  propiedades: '/propiedades',
  servicios: '/servicios',
  nosotros: '/nosotros',
  avaluoPropiedad: '/avaluo-de-propiedad',
  login: '/login',
  register: '/register',
  app: '/app',
  dashboard: '/app/dashboard',
  crm: '/app/crm',
  analytics: '/app/analytics',
  aiAssistant: '/app/ai-assistant',
  campaigns: '/app/campaigns',
  documents: '/app/documents',
  scoring: '/app/scoring',
  qr: '/app/qr',
  notifications: '/app/notifications',
  users: '/app/users',
  roles: '/app/roles',
  settings: '/app/settings',
  workflows: '/app/workflows',
  // Proptech
  proptech: '/app/proptech',
  proptechProfile: '/app/proptech/profile',
  proptechValuations: '/app/proptech/valuations',
  proptechProperties: '/app/proptech/properties',
  proptechPropertyNew: '/app/proptech/properties/new',
  proptechMatching: '/app/proptech/matching',
  proptechVisits: '/app/proptech/visits',
  proptechContracts: '/app/proptech/contracts',
  proptechLeads: '/app/proptech/leads',
  proptechClients: '/app/proptech/clients',
  proptechSearch: '/app/proptech/search',
  proptechAnalytics: '/app/proptech/analytics',
  proptechSales: '/app/proptech/sales',
  proptechReports: '/app/proptech/reports',
  proptechMySales: '/app/proptech/my-sales',
  proptechAgents: '/app/proptech/agents',
  proptechAutoPost: '/app/proptech/auto-post',
  // Agent promo
  propiedadDetalle: '/propiedades/:id',
  agente: '/agente-inmobiliario',
  agentePago: '/agente-inmobiliario/pago',
  // Propietario landing
  propietario: '/propietario',
  // Financial Tools
  proptechFinancialTools: '/app/proptech/financial-tools',
  financialCalculators: '/finanzas',
} as const;
