export const ROUTES = {
  home: '/',
  login: '/login',
  app: '/app',
  dashboard: '/app/dashboard',
  crm: '/app/crm',
  analytics: '/app/analytics',
  aiAssistant: '/app/ai-assistant',
  campaigns: '/app/campaigns',
  documents: '/app/documents',
  scoring: '/app/scoring',
  qr: '/app/qr',
  notifications: '/app/notifications',
  users: '/app/users',
  roles: '/app/roles',
  settings: '/app/settings',
  workflows: '/app/workflows',
  // Proptech
  proptech: '/app/proptech',
  proptechProperties: '/app/proptech/properties',
  proptechMatching: '/app/proptech/matching',
  proptechVisits: '/app/proptech/visits',
  proptechContracts: '/app/proptech/contracts',
  proptechLeads: '/app/proptech/leads',
  proptechClients: '/app/proptech/clients',
  proptechAnalytics: '/app/proptech/analytics',
} as const;
