export enum ModuleName {
  AiAssistant = 'ai-assistant',
  Analytics = 'analytics',
  Auth = 'auth',
  Campaigns = 'campaigns',
  Crm = 'crm',
  Dashboard = 'dashboard',
  Documents = 'documents',
  Geolocation = 'geolocation',
  Notifications = 'notifications',
  Permissions = 'permissions',
  Qr = 'qr',
  Roles = 'roles',
  Scoring = 'scoring',
  Settings = 'settings',
  Tenants = 'tenants',
  Users = 'users',
  Wallets = 'wallets',
}
